-- // ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
-- // █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

-- See https://wiki.hyprland.org/Configuring/Animations/
-- credits: https://github.com/prasanthrangan/hyprdots

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    animations = {
        enabled = false,
    },
})

