-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local background = "rgb(161616)"
local foreground = "rgb(DCDCDC)"
local red = "rgb(F25C5C)"
local yellow = "rgb(FF9C6A)"
local green = "rgb(75BD7D)"
