-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local colors = require("extras.plugins.hyprbars_colors")

hl.config({
    plugin = {
        hyprbars = {
            enabled = yes,
            bar_color = "rgba(0a0a0aff)",
            bar_height = 30,
            bar_blur = no,
            bar_title_enabled = yes,
            bar_text_size = 15,
            bar_text_weight =  bold,
            bar_text_font = "Outfit",
            bar_text_align = left,
            bar_buttons_alignment = right,
            bar_part_of_window = yes,
            bar_precedence_over_border = yes,
            bar_padding = 14,
            bar_button_padding = 12,
            icon_on_hover = no,
        },
    },
})


hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 28,
    icon = "󰅖",
    action = "hyprctl dispatch killactive",

})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 21,
    icon = "󱓼",
    action = "hyprctl dispatch fullscreen 1",
})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 24,
    icon = "",
    action = "hyprctl dispatch movetoworkspace special",
})
