-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local background = "rgb(161616)"

local foreground = "rgb(DCDCDC)"

local red = "rgb(F25C5C)"

local yellow = "rgb(FF9C6A)"

local green = "rgb(75BD7D)"
