-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local background = "rgb(16161A)"
local foreground = "rgb(DCDFE4)"
local red = "rgb(F25C5C)"
local yellow = "rgb(FF9C6A)"
local green = "rgb(75BD7D)"
