-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: /home/bypass/Documents/hyprbar-styles/windows.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("extras.plugins.windows")
