-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local colors = require("extras.plugins.hyprbars_colors")

hl.config({
    plugin = {
        hyprbars = {
            enabled = true,
            bar_color = "rgba(0f0f0fff)",
            bar_height = 34,
            bar_blur = false,
            bar_title_enabled = true,
            bar_text_size = 14,
            bar_text_weight =  bold,
            bar_text_font = "Space Grotesk SemiBold",
            bar_text_align = "left",
            bar_buttons_alignment = "right",
            bar_part_of_window = true,
            bar_precedence_over_border = true,
            bar_padding = 14,
            bar_button_padding = 12,
            icon_on_hover = false,
        },
    },
})

hl.window_rule({
    name = "no-hyprbars-on-tiled",
    match = { float = false },
    ["hyprbars:no_bar"] = true,
})


hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 28,
    icon = "󰅖",
    action = "hyprctl dispatch 'hl.dsp.window.close()'",

})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 21,
    icon = "󱓼",
    action = "hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = 1 })'",
})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 24,
    icon = "",
    action = "hyprctl dispatch 'hl.dsp.window.move({ workspace = \"special:discord\", follow = false })'",
})
