-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = colors.conf -> requires manual conversion
local colors = require("extras.plugins.hyprbars_colors")
-- TODO: convert colors.conf to .lua and use require()

hl.config({
    plugin = {
        hyprbars = {
            bar_color = "rgba(101010ff)",
            bar_height = 32,
            bar_text_font = "Segoe UI Variable Static Text Medium",
            bar_blur = yes,
            bar_text_size = 12,
            bar_text_align = left,
            bar_title_enabled = yes,
            bar_buttons_alignment = right,
            bar_button_padding = 12,
            bar_padding = 14,
            bar_precedence_over_border = yes,
            bar_part_of_window = yes,
        },
    },
})


hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 24,
    icon = "",
    action = "hyprctl dispatch killactive",

})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 14,
    icon = "",
    action = "hyprctl dispatch fullscreen 1",
})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(ffffffff)",
    size = 22,
    icon = "",
    action = "hyprctl dispatch movetoworkspace special",
})
