-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    debug = {
        disable_logs = true,
        enable_stdout_logs = true,
    },
    ecosystem = {
        no_update_news = true,
    },
})

