-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- hyprlang2lua polyfills — runtime helpers reproducing
-- hyprlang behaviour the typed Lua API doesn't expose directly.

require("extras.plugins.borders-plus-plus")
require("extras.plugins.colors")
require("extras.plugins.hyprbars")
