-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("WINEDEBUG", "fixme-all")
hl.env("MANPAGER", "nvim +Man!")
hl.env("BAT_THEME", "base16")
hl.env("ANI_CLI_MODE", "dub")
hl.env("TERM", "xterm-256color")

hl.env("SHELL", "/usr/bin/fish")
hl.env("VISUAL", "nvim")
hl.env("EDITOR", "nvim")

hl.env("TERMINAL", "xdg-terminal-exec")
hl.env("XDG_UTILS_TERMINAL", "xdg-terminal-exec")
hl.env("BROWSER", "chromium")
hl.env("XDG_UTILS_BROWSER", "chromium")
hl.env("FILEMANAGER", "nautilus")
hl.env("XDG_UTILS_FILEMANAGER", "nautilus")

hl.env("HYPRSHOT_DIR", "/home/bypass/Pictures/Screenshots/")

hl.env("ARRPC_BRIDGE_PORT", "1338")
