-- Application Associations
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local TERMINAL = "foot"
local FILEMANAGER_GUI = "xdg-open ~"

-- Date/Time Popups
hl.bind("SUPER + T", hl.dsp.exec_cmd("notify-send -t 3500 \"Current Time: $(date +\"%I:%M %p\")\""), { description = "Show Time" })
hl.bind("SUPER + D", hl.dsp.exec_cmd("notify-send -t 3500 \"Current Date: $(date +\"%A, %B %d, %Y\")\""), { description = "Show Date" })

hl.bind("SUPER + SHIFT + Space", hl.dsp.exec_cmd("harmony-reload waybar toggle"), { description = "Toggle Dock" })

-- Session Actions
hl.bind("SUPER + ALT + L", hl.dsp.exec_cmd("hyprlock"), { dont_inhibit = true, description = "Lock screen" })
hl.bind("SUPER + F1", hl.dsp.exec_cmd("harmony-toggle-gamemode"), { dont_inhibit = true, description = "Toggle Game Mode" })
hl.bind("SUPER + CTRL + Space", hl.dsp.exec_cmd("~/.local/bin/omarchy-theme-bg-next"), { dont_inhibit = true, description = "Cycle wallpaper" })
hl.bind("SUPER + SHIFT + I", hl.dsp.exec_cmd("hyprpicker -f hex -a -n"), { dont_inhibit = true, description = "Open Color Picker" })
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("harmony-toggle-osk"), { dont_inhibit = true, description = "Open On-Screen Keyboard" })
hl.bind("SUPER + F2", hl.dsp.exec_cmd("harmony-toggle-tiling"), { description = "Toggle Window Tiling" })
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("fish -c \"harmony-theme-set-wallpaper $(zenity --file-selection --title='Select Wallpaper' --file-filter='*.jpg *.png *.jpeg')\""), { dont_inhibit = true, description = "Open Wallpaper Picker" })
hl.bind("SUPER + ALT + O", hl.dsp.exec_cmd("harmony-install"), { dont_inhibit = true, description = "Show Desktop Expose" })
hl.bind("SUPER + ALT + P", hl.dsp.exec_cmd("harmony-install-aur"), { dont_inhibit = true, description = "Show Desktop Expose" })

-- Applications
hl.bind("SUPER + B", hl.dsp.exec_cmd("$BROWSER"), { description = "Open Browser" })
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("$BROWSER --private-window --incognito"), { description = "Open Private Browser" })
hl.bind("SUPER + Return", hl.dsp.exec_cmd(TERMINAL), { description = "Open Terminal" })
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd(TERMINAL .. " -a float-no-pin"), { description = "Open Terminal" })
hl.bind("SUPER + SHIFT + ALT + Return", hl.dsp.exec_cmd(TERMINAL .. " -a float"), { description = "Open Terminal" })
hl.bind("SUPER + SHIFT + Escape", hl.dsp.exec_cmd(TERMINAL .. " -e btop"), { description = "Open btop" })
hl.bind("SUPER + E", hl.dsp.exec_cmd(FILEMANAGER_GUI), { description = "Open Nautilus" })
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd(TERMINAL .. " -a float-no-pin -e fish -c yazi"), { description = "Open yazi" })

-- Web Apps
hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("zeditor"), { description = "Open Zed" })
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("fish -c \"omarchy-launch-webapp https://claude.ai\""), { description = "Open Claude" })
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("fish -c \"omarchy-launch-webapp https://ardb.app\""), { dont_inhibit = true, description = "Open ARDB" })
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("fish -c \"omarchy-launch-webapp https://reddit.com/r/omarchy\""), { description = "Open Reddit" })
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("fish -c \"omarchy-launch-webapp https://mail.google.com\""), { description = "Open Gmail" })
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("fish -c \"omarchy-launch-webapp https://app.plex.tv/desktop/"), { description = "Open Plex" })
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_cmd("fish -c \"chromium --profile-directory=Default --app=\"https://play.geforcenow.com/mall/\" %U\""), { description = "Open GeForce Now" })

-- Wayscriber Bind
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("pkill -SIGUSR1 wayscriber discord"), { description = "Open Wayscriber" })

-- Super-Tab Functionality - Tab Between Workspaces
hl.bind("SUPER + TAB", hl.dsp.focus({ workspace = "e+1" }), { dont_inhibit = true, description = "Tab Between Workspaces" })
hl.bind("SUPER + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }), { dont_inhibit = true, description = "Tab Between Workspaces" })

-- Alt-Tab Functionality - Cycle Through Windows
hl.bind("ALT + TAB", hl.dsp.window.cycle_next({ next = true }), { description = "Cycle to next window" })
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ prev = true }), { description = "Cycle to previous window" })
hl.bind("ALT + TAB", hl.dsp.window.bring_to_top(), { description = "Reveal active window on top" })
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.bring_to_top(), { description = "Reveal active window on top" })

-- Screen Capture
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("fish -c \"harmony-screenshot --region\""), { locked = true, dont_inhibit = true, description = "Take a screenshot of a selected area" })

-- Notifications
hl.bind("SUPER + COMMA", hl.dsp.exec_cmd("makoctl dismiss"), { description = "Dismiss last notification" })
hl.bind("SUPER + SHIFT + COMMA", hl.dsp.exec_cmd("makoctl dismiss --all"), { description = "Dismiss all notifications" })
hl.bind("SUPER + CTRL + COMMA", hl.dsp.exec_cmd("makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send \"Silenced notifications\" || notify-send \"Enabled notifications\""), { description = "Toggle silencing notifications" })
hl.bind("SUPER + ALT + COMMA", hl.dsp.exec_cmd("makoctl invoke"), { description = "Invoke last notification" })

-- Special Workspaces (Hidden)
hl.bind("SUPER + SHIFT + Backspace", hl.dsp.window.move({ workspace = "special:discord", follow = false }), { dont_inhibit = true, description = "Move to Special Workspace" })
hl.bind("SUPER + Backspace", hl.dsp.workspace.toggle_special("discord"), { dont_inhibit = true, description = "Open Special Workspace" })

-- Windows
hl.bind("ALT + F4", hl.dsp.window.close(), { description = "Kill Active Window" })
hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Kill Active Window" })
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.close(), { description = "Kill Active Window" })
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle Fullscreen" })
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle Exclusive Fullscreen" })
hl.bind("SUPER + C", hl.dsp.window.float({ action = "toggle" }), { description = "Float Active Window" })
hl.bind("SUPER + Z", hl.dsp.layout("togglesplit"), { description = "Toggle Window Split Orientation" })

-- Window Navigation
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }), { description = "Navigate Window Focus Left" })
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }), { description = "Navigate Window Focus Right" })
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }), { description = "Navigate Window Focus Down" })
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }), { description = "Navigate Window Focus Up" })

-- Window Management
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }), { description = "Move Window Left" })
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "r" }), { description = "Move Window Right" })
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "d" }), { description = "Move Window Down" })
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }), { description = "Move Window Up" })

-- Move & Resize Windows
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { description = "Move Window" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { description = "Resize Window" })

-- Workspace Navigation
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }), { dont_inhibit = true, description = "Switch to Workspace 1" })
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }), { dont_inhibit = true, description = "Switch to Workspace 2" })
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }), { dont_inhibit = true, description = "Switch to Workspace 3" })
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }), { dont_inhibit = true, description = "Switch to Workspace 4" })
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }), { dont_inhibit = true, description = "Switch to Workspace 5" })
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }), { dont_inhibit = true, description = "Switch to Workspace 6" })
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }), { dont_inhibit = true, description = "Switch to Workspace 7" })
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }), { dont_inhibit = true, description = "Switch to Workspace 8" })
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }), { dont_inhibit = true, description = "Switch to Workspace 9" })
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }), { dont_inhibit = true, description = "Switch to Workspace 10" })

-- Workspace Management
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 1" })
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 2" })
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 3" })
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 4" })
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 5" })
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 6" })
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 7" })
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 8" })
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 9" })
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }), { dont_inhibit = true, description = "Move window to Workspace 10" })

-- Workspace Naviation (Scroll Wheel)
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e-1" }), { dont_inhibit = true, description = "Scroll Active Workspace Down" })
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e+1" }), { dont_inhibit = true, description = "Scroll Active Workspace Up" })

-- Media Keys (Function Keys)
local osdclient = "swayosd-client --monitor \"$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')\""
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(osdclient .. " --playerctl=play-pause"), { locked = true, repeating = true, dont_inhibit = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd(osdclient .. " --playerctl=pause"), { locked = true, repeating = true, dont_inhibit = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd(osdclient .. " --playerctl=next"), { locked = true, repeating = true, dont_inhibit = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(osdclient .. " --playerctl=previous"), { locked = true, repeating = true, dont_inhibit = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(osdclient .. " --output-volume raise"), { locked = true, repeating = true, dont_inhibit = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(osdclient .. " --output-volume lower"), { locked = true, repeating = true, dont_inhibit = true, description = "Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(osdclient .. " --output-volume mute-toggle"), { locked = true, repeating = true, dont_inhibit = true, description = "Mute" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(osdclient .. " --input-volume mute-toggle"), { locked = true, repeating = true, dont_inhibit = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(osdclient .. " --brightness +5"), { locked = true, repeating = true, dont_inhibit = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(osdclient .. " --brightness -5"), { locked = true, repeating = true, dont_inhibit = true })

-- Screen Zoom
hl.bind("SUPER + ALT + mouse_down", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.1')"), { dont_inhibit = true })
hl.bind("SUPER + ALT + mouse_up", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.9) | if . < 1 then 1 else . end')"), { dont_inhibit = true })

hl.bind("F9", hl.dsp.pass({ window = "class:^(vesktop)$" }), { locked = true, transparent = true, dont_inhibit = true })
hl.config({
    binds = {
        scroll_event_delay = 10,
    },
    -- Push-to-Talk button
    -- bindelp = , F9, exec, echo -ne '\007' && pamixer --default-source -t
})
