source = decoration/animations.conf
source = decoration/rounding.conf
source = decoration/borders.conf

decoration {
    rounding = $corner_radius
    rounding_power = 2
    dim_inactive = no

    shadow {
      enabled = no
      render_power = 16
      range = 10
      color = rgba(00000090)
    }
}
