-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: decoration/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.decoration.animations")
-- Source: decoration/rounding.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.decoration.rounding")

hl.config({
    decoration = {
        rounding = corner_radius,
        rounding_power = 2,
        dim_inactive = false,
        shadow = {
            enabled = false,
            render_power = 16,
            range = 10,
            color = "rgba(00000090)",
        },
    },
})
