-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: decoration/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.decoration.animations")

require("core.decoration.blur")

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        dim_inactive = false,
        shadow = {
            enabled = true,
            render_power = 16,
            range = 10,
            color = "rgba(00000090)",
        },
        blur = {
            enabled = true,

        },
    },
})
