-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    layout = {
        single_window_aspect_ratio = "0 0",
    },
    dwindle = {
        preserve_split = true,
    },
    master = {
        smart_resizing = true,
        drop_at_cursor = true,
    },
    general = {
        layout = "dwindle",
        gaps_in = 1,
        gaps_out = 1,
        resize_on_border = false,
        border_size = 1,
        snap = {
            enabled = false,
        },
    },
})

