-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    misc = {
        vrr = true,
        focus_on_activate = true,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        enable_swallow = true,
        swallow_regex = "(foot|kitty|[Aa]lacritty|[Gg]hostty|Nautilus)",
        disable_splash_rendering = false,
        middle_click_paste = false,
        disable_hyprland_logo = true,
        force_default_wallpaper = 0,
        on_focus_under_fullscreen = true,
        allow_session_lock_restore = true,
        initial_workspace_tracking = true,
        font_family = "Iosevka",
    },
    render = {
        direct_scanout = true,
    },
})

