-- Setup XDG
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Play startup sound :D

-- Start Polkit

-- Initialize wallpaper (yin)

-- Start Hypridle

-- Start Voxtype

-- Start drive mount applet

-- Start mpd server

-- Start wl-clip-persist

-- Start KDE connect

-- Start system tray applets

-- Start Taskbar

-- Start Mouse Battery Alert

-- Start Vicinae Server

-- Load Audio Fix

-- Start clock widget
-- exec-once = ignis init &

-- Load Discord

-- Start arrpc
-- exec-once = sleep 3 && fish -c arrpc &

-- Load Hyprland Plugins
-- exec-once = hyprpm reload

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.local/share/harmony/bin/harmony-initialize xdg")
    hl.exec_cmd("sleep 3 && /usr/bin/mpv --no-video --volume=50 /usr/share/sounds/startup.wav 2>/dev/null")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("~/.local/share/harmony/bin/harmony-initialize wp")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("voxtype daemon &")
    hl.exec_cmd("udiskie -an &")
    hl.exec_cmd("mpd > ~/.logs/mpd.log &")
    hl.exec_cmd("wl-clip-persist --clipboard both &")
    hl.exec_cmd("kdeconnectd &")
    hl.exec_cmd("kdeconnect-indicator &")
    hl.exec_cmd("jamesdsp --tray &")
    hl.exec_cmd("mako &")
    hl.exec_cmd("swayosd-server &")
    hl.exec_cmd("~/.local/share/harmony/bin/harmony-reload i3 &")
    hl.exec_cmd("~/.local/bin/mxw-low-battery-alert &")
    hl.exec_cmd("vicinae server &")
    hl.exec_cmd("~/.local/bin/audio-fix &")
    hl.exec_cmd("sleep 10 && vesktop &")
end)
