-- Dialogs - Floating
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Confirm to replace files)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Customize Look and Feel)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Extract)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(File Operation Progress)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(File Properties)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Open File)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Save As)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    float = true,
})

-- Dialogs - Centering
hl.window_rule({
    match = {
        title = "(Confirm to replace files)",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "(Customize Look and Feel)",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "(Extract)",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "(File Operation Progress)",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "(Open File)",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "(Save As)",
    },
    center = true,
})

-- Dialogs - Floating (User Apps)
hl.window_rule({
    match = {
        class = "^(AppRun.wrapped)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^([Rr]ofi)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.Calendar)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.Weather)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.FileRoller)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(dconf-editor)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.interversehq.qView)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Home - Lunar Client)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(Vencord QuickCSS Editor)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(nwg-look)",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "(swayimg)",
    },
    float = true,
})

-- Dialogs - No Hyprbars

hl.window_rule({
    match = {
        class = "^(qt6ct)$",
    },
    float = true,
    size = "605 560",
})

hl.window_rule({
    match = {
        class = "^(Screensaver)$",
    },
    fullscreen_state = "3",
})

