-- Layer Rules - no_anim
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.layer_rule({
    match = { namespace = "no_anim yes" },
    -- TODO: manual review — unmapped layer rule: "match:namespace selection"
    -- TODO: manual review — unmapped layer rule: "match:namespace overview"
    -- TODO: manual review — unmapped layer rule: "match:namespace anyrun"
    -- TODO: manual review — unmapped layer rule: "match:namespace popup.*"
    -- TODO: manual review — unmapped layer rule: "match:namespace hyprpicker"
    -- TODO: manual review — unmapped layer rule: "match:namespace no_anim"
    -- TODO: manual review — unmapped layer rule: "match:namespace walker"
    -- TODO: manual review — unmapped layer rule: "match:namespace vicinae"
})

-- Layer Rules - blur
hl.layer_rule({
    match = { namespace = "blur yes" },
    -- TODO: manual review — unmapped layer rule: "match:namespace launcher"
    -- TODO: manual review — unmapped layer rule: "match:namespace notifications"
    -- TODO: manual review — unmapped layer rule: "match:namespace walker"
    -- TODO: manual review — unmapped layer rule: "match:namespace waybar"
    -- TODO: manual review — unmapped layer rule: "match:namespace ignis.*"
    -- TODO: manual review — unmapped layer rule: "match:namespace swayosd"
    -- TODO: manual review — unmapped layer rule: "match:namespace vicinae"
    -- TODO: manual review — unmapped layer rule: "match:namespace nwg-dock"
})

-- Layer Rules - ignore_alpha
hl.layer_rule({
    match = { namespace = "ignore_alpha 0.5" },
    -- TODO: manual review — unmapped layer rule: "match:namespace notifications"
    -- TODO: manual review — unmapped layer rule: "match:namespace walker"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0" },
    -- TODO: manual review — unmapped layer rule: "match:namespace vicinae"
})

hl.layer_rule({
    match = { namespace = "ignore_alpha 0.5" },
    -- TODO: manual review — unmapped layer rule: "match:namespace ignis.*"
    -- TODO: manual review — unmapped layer rule: "match:namespace nwg-dock"
})

-- Layer Rules - On Lockscreen
hl.layer_rule({
    match = { namespace = "above_lock 1" },
    -- TODO: manual review — unmapped layer rule: "match:namespace swayosd"
    -- TODO: manual review — unmapped layer rule: "match:namespace notifications"
})

