-- Show Hyprbars on floating windows
-- # windowrule = match:floating:0, decorate off

-- Hide Hyprbars on specific windows
-- windowrule = match:title ^(winetricks)$, hyprbars:nobar yes
-- windowrule = match:class ^(ONLYOFFICE.*)$, decorate off
-- windowrule = match:title:^(Wootility Web)$, decorate off
-- windowrule = match:class ^(Google-chrome)$, decorate off
-- windowrule = match:class ^(ueberzugpp_.*)$, decorate off
-- windowrule = match:title:^(Unlock Keyring)(.*)$, decorate off
-- windowrule = match:class ^(zenity)$, title:^(Winetricks.*)$, decorate off
-- windowrule = match:class ^(org.gnome.FileRoller), decorate off
-- windowrule = match:class ^(org.gnome.FileRoller), title:^(New Folder)$, decorate off
-- windowrule = match:class ^(xdg-desktop-portal-gtk), title:^(Open Files)$, decorate off

-- Picture-in-Picture
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        tag = "pip",
    },
    float = true,
    pin = true,
    size = "480 270",
    keep_aspect_ratio = true,
    border_size = 0,
    rounding = 0,
    opacity = "1 1",
    move = "1430 10",
})

hl.window_rule({
    match = {
        title = "^(.*- YouTube.*)$",
    },
    opacity = 1,
})

hl.window_rule({
    match = {
        title = "^(Watch.*online free.*)$",
    },
    opacity = 1,
})

hl.window_rule({
    match = {
        title = "^(▶.*)$",
    },
    opacity = 1,
})

