windowrule = match:title ^(Picture-in-Picture)$, tag +pip
windowrule = match:title ^(Picture in picture)$, tag +pip

windowrule = match:tag pip, min_size 1 1
windowrule = match:tag pip, move 1323 28
windowrule = match:tag pip, size 592 269
windowrule = match:tag pip, move 1436 28
windowrule = match:tag pip, move 1436 3
windowrule = match:tag pip, size 480 270
windowrule = match:tag pip, opacity 1 1
windowrule = match:tag pip, border_size 1
windowrule = match:tag pip, rounding 0
windowrule = match:tag pip, keep_aspect_ratio no
windowrule = match:tag pip, no_initial_focus yes
windowrule = match:tag pip, decorate yes
windowrule = match:tag pip, float yes
windowrule = match:tag pip, pin yes
