set -g @nova-pane-active-border-style "#131318"
set -g @nova-pane-border-style "#131318"
set -g @nova-status-style-bg "#131318"
set -g @nova-status-style-fg "#e1e0f9"
set -g @nova-status-style-active-bg "#131318"
set -g @nova-status-style-active-fg "#bfc1ff"
set -g @nova-status-style-double-bg "#131318"
set -g @nova-segment-mode-colors "#131318 #e1e0ff"
set -g @nova-segment-datetime-colors "#131318 #e1e0ff"
