set -g @nova-pane-active-border-style "#0f1417"
set -g @nova-pane-border-style "#0f1417"
set -g @nova-status-style-bg "#0f1417"
set -g @nova-status-style-fg "#d2e5f4"
set -g @nova-status-style-active-bg "#0f1417"
set -g @nova-status-style-active-fg "#91cef4"
set -g @nova-status-style-double-bg "#0f1417"
set -g @nova-segment-mode-colors "#0f1417 #c5e7ff"
set -g @nova-segment-datetime-colors "#0f1417 #c5e7ff"
