set -g @nova-pane-active-border-style "#151218"
set -g @nova-pane-border-style "#151218"
set -g @nova-status-style-bg "#151218"
set -g @nova-status-style-fg "#ecddf7"
set -g @nova-status-style-active-bg "#151218"
set -g @nova-status-style-active-fg "#d9bafa"
set -g @nova-status-style-double-bg "#151218"
set -g @nova-segment-mode-colors "#151218 #eedbff"
set -g @nova-segment-datetime-colors "#151218 #eedbff"
