# Aliases - Configuration
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# Aliases - System Tools
alias ani="ani-cli --dub --skip"
alias c="config"
alias cat="bat -p"
alias cfg="config"
alias cl="clear"
alias clock="tty-clock -t -c -b -B -C 7"
alias cp="cp -irv"
alias ducks="du -cks * | sort -rn | head"
alias edit="zed ."
alias ex="exit"
alias f="fetch"
alias fl="flavours"
alias fp="flatpak"
alias g="git"
alias grep="rg"
alias hc="hyprctl"
alias hl="hyprctl"
alias hrl="harmony-reload"
alias hpm="hyprpm"
alias hs="hyprshade"
alias hx.="helix ."
alias hx="helix"
alias icons="papirus-folders -t Papirus-Dark -C $1"
alias l="ls"
alias la="ls -la"
alias lg="lazygit"
alias ll="ls -l"
alias ls="eza --icons"
alias lsa="ls -la"
alias m.="micro ."
alias m="micro"
alias mkdir="mkdir -pv"
alias moviebox="ssh schaefer@10.0.0.196"
alias mxw="sudo -n mxw"
alias nano="micro"
alias ncmp="ncmpcpp"
alias o.="open . & disown"
alias o="open "
alias q="exit"
alias run0="run0 --background=00 "
alias si="swayimg"
alias soundux="flatpak run io.github.Soundux"
alias t="todo"
alias tree="ls --tree"
alias unset="set --erase"
alias v="nvim"
alias vote="ssh aur@aur.archlinux.org vote $1"
alias vps="ssh root@imbypass.pw"
alias wg++="x86_64-w64-mingw32-g++"
alias x="exit"
alias yay="paru"
alias ytdl="yt-dlp --format \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]\" $1"
alias z.="z ."
alias z="zeditor"
alias ⏲️="date"
