# Aliases - Configuration
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# Aliases - System Tools
alias ...="cd ../.."
alias ani="ani-cli --dub --skip"
alias c="config"
alias cat="bat -p"
alias cb="/home/bypass/.var/app/com.usebottles.bottles/data/bottles/bottles/Battle.net/drive_c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_classic_era_/CurseBreaker $1"
alias cfg="config"
alias cl="clear"
alias clock="tty-clock -t -c -b -B -C 7"
alias cp="cp -irv"
alias ducks="du -cks * | sort -rn | head"
alias edit="zed ."
alias ex="exit"
alias f="fetch"
alias fl="flavours"
alias fp="flatpak"
alias g="git"
alias grep="rg"
alias h="harmonyctl"
alias harmony="harmonyctl"
alias hc="hyprctl"
alias hl="hyprctl"
alias hpm="hyprpm"
alias hs="hyprshade"
alias hx.="helix ."
alias hx="helix"
alias icons="papirus-folders -t Papirus-Dark -C $1"
alias l="ls"
alias la="ls -la"
alias lg="lazygit"
alias ll="ls -l"
alias ls="eza --icons"
alias lsa="ls -la"
alias m.="micro ."
alias m="micro"
alias mkdir="mkdir -pv"
alias mse="ms-edit"
alias msedit="ms-edit"
alias moviebox="ssh schaefer@10.0.0.196"
alias nano="micro"
alias ncmp="ncmpcpp"
alias o.="open ."
alias o="open"
alias pywal="wal -i ~/.local/share/wallpapers/.wallpaper && fl apply match-wallpaper&& tmux source ~/.config/tmux/tmux.conf"
alias q="exit"
alias run0="run0 --background=00 "
alias si="swayimg"
alias soundux="flatpak run io.github.Soundux"
alias t="todo"
alias tree="ls --tree"
alias unset="set --erase"
alias v="nvim"
alias vote="ssh aur@aur.archlinux.org vote $1"
alias vps="ssh root@imbypass.pw"
alias wg++="x86_64-w64-mingw32-g++"
alias wp="swww img $1"
alias wpe='mpvpaper -p -o "--loop=inf --vf-add=fps=30:round=near --framedrop=vo" "*" $1'
alias x="exit"
alias yay="paru"
alias ytdl="yt-dlp --format \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]\" $1"
alias z.="zed ."
alias z="zed"
alias ⏲️="date"
