# Aliases - Configuration
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# Aliases - System Tools
alias ⏲️="date"
alias ...="cd ../.."
alias ani="ani-cli --dub --skip"
alias b="bde"
alias cat="bat -p"
alias cfg="config"
alias cl="clear"
alias cb="/home/bypass/.var/app/com.usebottles.bottles/data/bottles/bottles/Battle.net/drive_c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_classic_era_/CurseBreaker $1"
alias clock="tty-clock -t -c -b -B -C 4"
alias ducks="du -cks * | sort -rn | head"
alias ex="exit"
alias f="fetch"
alias fl="flavours"
alias fp="flatpak"
alias g="git"
alias grep="rg"
alias h="hyprctl"
alias hpm="hyprpm"
alias hs="hyprshade"
alias hx="helix"
alias hx.="helix ."
alias icons="papirus-folders -t Papirus-Dark -C $1"
alias l="ls"
alias ll="ls -l"
alias la="ls -la"
alias lg="lazygit"
alias ls="eza --icons"
alias lsa="ls -la"
alias m="micro"
alias m.="micro ."
alias moviebox="ssh schaefer@10.0.0.196"
alias nano="micro"
alias ncmp="ncmpcpp"
alias o="open"
alias q="exit"
alias soundux="flatpak run io.github.Soundux"
alias t="todo"
alias tree="ls --tree"
alias unset="set --erase"
alias v="nvim"
alias vps="ssh root@imbypass.pw"
alias wg++="x86_64-w64-mingw32-g++"
alias wp="swww img $1"
alias x="exit"
alias yay="paru"
alias ytdl="yt-dlp --format \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]\" $1"
alias z="zed"
alias z.="zed ."
