-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "phinger-cursors-dark")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        shadow = {
            range = 10,
            render_power = 4,
        },
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        allow_tearing = true,
        snap = {
            enabled = false,
        },
    },
    misc = {
        animate_mouse_windowdragging = true,
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = false,
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "1920x1080@144.00Hz",
    position = "0x120",
    scale = 1,
    transform = 1,
    cm = "srgb",
})
