-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    decoration = {
        blur = {
            enabled = true,
            size = 3,
            passes = 2,
            new_optimizations = true,
            xray = false,
            vibrancy = 0.33,
            noise = 0,
        },
    },
})

