-- Core Hyprland Configuration
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

require("core.binds")
require("core.decoration")
require("core.environment")
require("core.input")
require("core.layout")
-- require("core.monitor")
require("core.misc")
require("core.startup")

-- Extra Hyprland Configuration
require("extras.cursor")
require("extras.general")
require("extras.plugins")
require("extras.rules")
require("extras.user")

require("input")
require("monitors")
require("workspaces")

-- Source: vicinae.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("vicinae")
hl.config({
    general = {
        col = {
            active_border = "rgba(2f333bff)",
            inactive_border = "rgba(2f333bff)",
        },
    },
    animations = {
        enabled = true,
    }
    -- Theme Hook
    -- source = ~/.config/omarchy/current/theme/hyprland.conf
    -- MacOS Input Sens
    -- Vicinae Binds
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
