-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/omarchy/current/theme/hyprlock.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprlock")

-- TODO: manual review — unknown section 'background {' on line 3

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 1.8,
    bezier = "linear",
})
hl.curve("linear", { type = "bezier", points = { { 1, 1 }, { 0, 0 } } })

-- TODO: manual review — unknown section 'label {' on line 21

-- TODO: manual review — unknown section 'label {' on line 35

-- TODO: manual review — unknown section 'input-field {' on line 49

-- TODO: manual review — unknown section 'image {' on line 76

-- TODO: manual review — unknown section 'label {' on line 90

-- TODO: manual review — unknown section 'label {' on line 103

-- TODO: manual review — unknown section 'label {' on line 116

-- TODO: manual review — unknown section 'label {' on line 129

-- TODO: manual review — unknown section 'auth {' on line 141
hl.config({
    animations = {
        enabled = true,
    },
    -- DATE
    -- TIME
    -- INPUT FIELD
    -- PROFILE IMAGE
    -- USERNAME
    -- REBOOT
    -- POWER OFF
    -- SUSPEND
})

