-- Core Hyprland Configuration
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: core/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.binds")
-- Source: core/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.decoration")
-- Source: core/environment.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.environment")
-- Source: core/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.input")
-- Source: core/layout.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.layout")
-- Source: core/monitor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.monitor")
-- Source: core/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.misc")
-- Source: core/startup.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.startup")

-- Extra Hyprland Configuration
-- Source: extras/cursor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("extras.cursor")
-- Source: extras/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("extras.general")
-- Source: extras/plugins.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("extras.plugins")
-- Source: extras/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("extras.rules")
-- Source: extras/user.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("extras.user")

-- xdg

-- Theme Colors
-- Source: ~/.config/omarchy/current/theme/hyprland_colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("hyprland_colors")
-- Source: ~/.config/omarchy/current/theme/hyprland_border.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("hyprland_border")

-- Source: input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")

-- Source: vicinae.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("vicinae")
hl.config({
    general = {
        col = {
            active_border = "#555555",
        },
        border_size = 2,
    },
    group = {
        col = {
            border_active = activeBorderColor,
        },
    },
    decoration = {
        dim_inactive = false,
        blur = {
            enabled = false,
        },
        shadow = {
            enabled = false,
        },
    },
    animations = {
        enabled = false,
    }
    -- Theme Hook
    -- source = ~/.config/omarchy/current/theme/hyprland.conf
    -- MacOS Input Sens
    -- Vicinae Binds
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
