-- Generated by nwg-displays on 2026-06-22 at 18:33:48. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@144.0",
    position = "0x207",
    scale = 1.0,
    transform = 1
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144.01",
    position = "1080x427",
    scale = 1.0
})
