sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-activities.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-activities.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-android.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-android.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-apple.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-apple.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-applications.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-applications.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-arduino.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-arduino.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-backup.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-backup.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-books.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-books.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-cd.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-cd.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-code.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-code.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-desktop.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-desktop.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-development.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-development.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-docker.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-docker.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-documents-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-documents-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-documents.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-documents.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-download-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-download-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-download.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-download.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-drag-accept.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-drag-accept.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-dropbox.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-dropbox.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-favorites.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-favorites.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-games.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-games.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-git.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-git.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-github.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-github.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-gitlab.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-gitlab.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-gnome.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-gnome.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-google-drive.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-google-drive.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-image-people.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-image-people.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-important.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-important.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-java.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-java.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-kde.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-kde.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-linux.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-linux.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-locked.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-locked.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-mail-cloud.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-mail-cloud.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-mail.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-mail.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-mega.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-mega.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-meocloud.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-meocloud.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-music-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-music-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-music.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-music.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-network.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-network.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-nextcloud.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-nextcloud.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-notes.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-notes.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-obsidian.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-obsidian.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-onedrive.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-onedrive.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-owncloud.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-owncloud.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-pcloud.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-pcloud.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-photo.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-photo.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-pictures-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-pictures-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-pictures.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-pictures.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-print.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-print.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-private.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-private.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-projects.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-projects.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-publicshare-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-publicshare-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-recent.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-recent.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-remote-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-remote-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-remote.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-remote.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-script.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-script.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-snap.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-snap.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-steam.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-steam.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-sync.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-sync.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-syncthing.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-syncthing.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-systemd.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-systemd.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-tar.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-tar.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-templates-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-templates-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-templates.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-templates.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-torrent.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-torrent.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-unlocked.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-unlocked.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-vbox.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-vbox.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-video.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-video.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-videos-open.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-videos-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-visiting.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-visiting.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-vmware.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-vmware.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-wifi.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-wifi.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-wine.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-wine.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16-yandex-disk.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16-yandex-disk.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/folder-base16.svg /usr/share/icons/Papirus-Dark/22x22/places/folder-base16.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/user-base16-desktop.svg /usr/share/icons/Papirus-Dark/22x22/places/user-base16-desktop.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/user-base16-home-open.svg /usr/share/icons/Papirus-Dark/22x22/places/user-base16-home-open.svg
 sudo ln ~/.local/share/icons/Papirus-Dark/22x22/places/user-base16-home.svg /usr/share/icons/Papirus-Dark/22x22/places/user-base16-home.svg
