# Configuration for flavours

shell = "fish -c '{}'"

### HARMONY LOGO ###
[[items]]
file = "~/.local/share/harmony/logo.svg"
template = "harmony"
rewrite = true

### PHOCUS GTK THEME ###
[[items]]
file = "~/.themes/phocus/scss/gtk-3.0/_colors.scss"
template = "phocus"
rewrite = false
start = "// start colors"
end = "// end colors"
hook = "~/.local/bin/harmonyctl reload gtk"

### GTK 4.0 THEME ###
[[items]]
#file = "~/.themes/phocus/gtk-4.0/gtk.css"
file = "~/.config/gtk-4.0/gtk.css"
template = "gtk4"
rewrite = false
start = "/* start colors */"
end = "/* end colors */"
hook = "~/.local/bin/harmonyctl reload gtk"

### QT6 THEME ###
[[items]]
file = "~/.config/qt6ct/colors/base16.conf"
template = "qt6ct"
rewrite = true

### VESKTOP ###
[[items]]
file = "~/.config/vesktop/settings/quickCss.css"
template = "vesktop"
rewrite = true

### NCSPOT ###
[[items]]
file = "~/.config/ncspot/config.toml"
template = "ncspot"
rewrite = true

### FIREFOX ###
[[items]]
file = "/home/bypass/.mozilla/firefox/li1xg7z9.default-release/chrome/base16.css"
template = "firefox"
rewrite = false
start = "/* start colors */"
end = "/* end colors */"

### FZF ###
[[items]]
file = "~/.config/fish/conf.d/fzf.fish"
template = "fzf"
subtemplate = "base16-fish"
rewrite = true

### MPV ###
[[items]]
file = "~/.config/mpv/mpv.conf"
template = "mpv"
rewrite = false
start = "# start colors"
end = "# end colors"

### STEAM ###
[[items]]
file = "~/.local/share/adwaita-steam/adwaita/colorthemes/base16/base16.css"
template = "steam"
rewrite = true
hook = "~/.local/bin/harmonyctl reload steam"

### ZED EDITOR ###
[[items]]
file = "~/.config/zed/themes/base16-flavours.json"
template = "zed"
rewrite = true

### VS CODE - OSS ###
[[items]]
file = "~/.vscode-oss/extensions/tintedtheming.base16-tinted-themes-0.27.0-universal/themes/base16/base16-dynamic.json"
template = "vscode"
rewrite = true

### HYPRLAND ###
[[items]]
file = "~/.config/hypr/extras/colors.conf"
template = "hyprland"
rewrite = true

### MAKO DAEMON ###
[[items]]
file = "~/.config/mako/colors"
template = "mako"
rewrite = true
hook = "~/.local/bin/harmonyctl reload mako"

### WALKER ###
[[items]]
file = "~/.config/walker/themes/base16/colors.css"
template = "walker"
rewrite = false
start = "/* start flavours */"
end = "/* end flavours */"
hook = "~/.local/bin/harmonyctl reload walker"

### FOOT TERMINAL ###
[[items]]
file = "~/.config/foot/colors.ini"
template = "foot"
rewrite = true

### TMUX ###
[[items]]
file = "~/.config/tmux/base16.conf"
template = "tmux"
subtemplate = "default"
rewrite = true
hook = "tmux source ~/.config/tmux/base16.conf"

### FISH SHELL ###
[[items]]
file = "~/.config/fish/themes/base16.theme"
template = "fish"
rewrite = true

### HELIX EDITOR ###
[[items]]
file = "~/.config/helix/themes/base16.toml"
template = "helix"
rewrite = true

### MICRO EDITOR ###
[[items]]
file = "~/.config/micro/colorschemes/base16.micro"
template = "micro"
rewrite = true

### SPOTIFY ###
[[items]]
file = "~/.config/spicetify/Themes/base16/color.ini"
template = "spotify"
rewrite = true
hook = "~/.local/bin/harmonyctl update spotify"
light = false

### NEOVIM ###
[[items]]
file = "~/.config/nvim/lua/config/base16.lua"
template = "nvim"
rewrite = false
start = "-- start colors"
end = "-- end colors"

### SWAYIMG BACKGROUND ###
[[items]]
file = "~/.config/swayimg/config"
template = "swayimg"
rewrite = false
start = "# Window background color (RGBA)"
end = "# Background for transparent images (grid/RGBA)"

### MOUSE COLORS ###
[[items]]
file = "~/.local/share/harmony/BASE16"
template = "mouse-colors"
rewrite = true

### BONGOCAT BAR PET ###
# [[items]]
# file = "~/.config/bongocat/config"
# template = "bongocat"
# rewrite = false
# start = "# start colors"
# end = "# end colors"
# hook = "~/.local/bin/harmonyctl reload bongocat"

### WAYBAR ###
[[items]]
file = "~/.config/waybar/base16.css"
template = "waybar"
rewrite = true
hook = "sleep .5 &&  ~/.local/bin/harmonyctl reload waybar"

# ### NWG-MENU ###
# [[items]]
# file = "~/.config/nwg-panel/menu-start.css"
# template = "nwg-menu"
# rewrite = true
# hook = "~/.local/bin/harmonyctl reload waybar"

# ### GHOSTTY TERMINAL ###
# [[items]]
# file = "~/.config/ghostty/themes/base.conf"
# template = "ghostty"
# rewrite = true
# hook = "~/.local/bin/harmonyctl reload ghostty"

# ### NWG DOCK ###
# [[items]]
# file = "~/.config/nwg-dock-hyprland/colors.css"
# template = "nwg-dock"
# rewrite = true
# hook = "~/.local/bin/harmonyctl reload dock"
