[mgr]
show_hidden = false
ratio = [1, 3, 5]
sort_by = 'natural'
sort_reverse = false
sort_dir_first = true

[opener]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
edit = [{ run = 'micro "$@"', block = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
