use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#1a1515"
primary = "#dcc9bc"
secondary = "#725a5a"
title = "#614f76"
playing = "#614f76"
playing_selected = "#614f76"
playing_bg = "#1a1515"
highlight = "#dcc9bc"
highlight_bg = "#2d2424"
error = "#2d2424"
error_bg = "#cf223e"
statusbar = "#614f76"
statusbar_progress = "#614f76"
statusbar_bg = "#1a1515"
cmdline = "#dcc9bc"
cmdline_bg = "#1a1515"
search_match = "#614f76"