use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#0a0a0c"
primary = "#b2b5b3"
secondary = "#363638"
title = "#7aa2f7"
playing = "#7aa2f7"
playing_selected = "#7aa2f7"
playing_bg = "#0a0a0c"
highlight = "#b2b5b3"
highlight_bg = "#121215"
error = "#121215"
error_bg = "#f7768e"
statusbar = "#7aa2f7"
statusbar_progress = "#7aa2f7"
statusbar_bg = "#0a0a0c"
cmdline = "#b2b5b3"
cmdline_bg = "#0a0a0c"
search_match = "#7aa2f7"