use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#151515"
primary = "#b2b5b3"
secondary = "#373737"
title = "#50a4e7"
playing = "#50a4e7"
playing_selected = "#50a4e7"
playing_bg = "#151515"
highlight = "#b2b5b3"
highlight_bg = "#212121"
error = "#212121"
error_bg = "#e55f86"
statusbar = "#50a4e7"
statusbar_progress = "#50a4e7"
statusbar_bg = "#151515"
cmdline = "#b2b5b3"
cmdline_bg = "#151515"
search_match = "#50a4e7"