use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "black"
primary = "white"
secondary = "white"
title = "green"
playing = "green"
playing_selected = "black"
playing_bg = "black"
highlight = "black"
highlight_bg = "cyan"
error = "red"
error_bg = "red"
statusbar = "magenta"
statusbar_progress = "magenta"
statusbar_bg = "black"
cmdline = "black"
cmdline_bg = "black"
search_match = "white"
