use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#0f0f0f"
primary = "#b2b5b3"
secondary = "#3a3a3a"
title = "#70abff"
playing = "#70abff"
playing_selected = "#70abff"
playing_bg = "#0f0f0f"
highlight = "#b2b5b3"
highlight_bg = "#1d1d1d"
error = "#1d1d1d"
error_bg = "#ff5454"
statusbar = "#70abff"
statusbar_progress = "#70abff"
statusbar_bg = "#0f0f0f"
cmdline = "#b2b5b3"
cmdline_bg = "#0f0f0f"
search_match = "#70abff"