use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#181515"
primary = "#b6a8a5"
secondary = "#6d5f5f"
title = "#4a5a8d"
playing = "#4a5a8d"
playing_selected = "#4a5a8d"
playing_bg = "#181515"
highlight = "#b6a8a5"
highlight_bg = "#221e1e"
error = "#221e1e"
error_bg = "#ca3f3f"
statusbar = "#4a5a8d"
statusbar_progress = "#4a5a8d"
statusbar_bg = "#181515"
cmdline = "#b6a8a5"
cmdline_bg = "#181515"
search_match = "#4a5a8d"