use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#07090d"
primary = "#acb0d0"
secondary = "#475070"
title = "#7aa2f7"
playing = "#7aa2f7"
playing_selected = "#7aa2f7"
playing_bg = "#07090d"
highlight = "#acb0d0"
highlight_bg = "#090b11"
error = "#090b11"
error_bg = "#f7768e"
statusbar = "#7aa2f7"
statusbar_progress = "#7aa2f7"
statusbar_bg = "#07090d"
cmdline = "#acb0d0"
cmdline_bg = "#07090d"
search_match = "#7aa2f7"