use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#05010c"
primary = "#c7cac2"
secondary = "#422e66"
title = "#a6b8ff"
playing = "#a6b8ff"
playing_selected = "#a6b8ff"
playing_bg = "#05010c"
highlight = "#c7cac2"
highlight_bg = "#0c041a"
error = "#0c041a"
error_bg = "#f07178"
statusbar = "#a6b8ff"
statusbar_progress = "#a6b8ff"
statusbar_bg = "#05010c"
cmdline = "#c7cac2"
cmdline_bg = "#05010c"
search_match = "#a6b8ff"