use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#151519"
primary = "#b2b5b3"
secondary = "#373741"
title = "#50a4e7"
playing = "#50a4e7"
playing_selected = "#50a4e7"
playing_bg = "#151519"
highlight = "#b2b5b3"
highlight_bg = "#212127"
error = "#212127"
error_bg = "#e55f86"
statusbar = "#50a4e7"
statusbar_progress = "#50a4e7"
statusbar_bg = "#151519"
cmdline = "#b2b5b3"
cmdline_bg = "#151519"
search_match = "#50a4e7"