windowrule = match:class ^(8bitdo\.exe)$, immediate on
windowrule = match:class ^(8bitdo\.exe)$, render_unfocused on
windowrule = match:class ^(8bitdo\.exe)$, float on
windowrule = match:class *(8bitdo.exe)$, immediate on
windowrule = match:class *(8bitdo.exe)$, render_unfocused on
windowrule = match:class *(8bitdo.exe)$, float on
