-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(8bitdo\\.exe)$",
    },
    immediate = true,
    render_unfocused = true,
    float = true,
})

hl.window_rule({
    match = {
        class = "*(8bitdo.exe)$",
    },
    immediate = true,
    render_unfocused = true,
    float = true,
})

