windowrule = match:class ^(chrome-ardb.app__-Default)$, float on
windowrule = match:class ^(chrome-ardb.app__-Default)$, size 1000 700
windowrule = match:class ^(chrome-arcraidersmaps.app__-Default)$, float on
windowrule = match:class ^(chrome-arcraidersmaps.app__-Default)$, size 1000 700
