-- # windowrule = immediate, title:^(Battle.net.*)$
-- windowrule = match:title ^(Battle.net.*)$, decorate off

-- windowrule = match:class ^(steam_app_0)$ title:^(World of Warcraft)$, fullscreen on
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(steam_app_0)$ title:^(World of Warcraft)$",
    },
    immediate = true,
    render_unfocused = true,
    content = "game",
    workspace = "8",
})

