windowrule = match:class ^(Blockbench)$, immediate on
windowrule = match:class ^(Blockbench)$, render_unfocused on
windowrule = match:class ^(Blockbench)$, content game
windowrule = match:class ^(Blockbench)$, workspace 3
