-- Amazon Luna
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(chrome-mdjpfbokiopdhidmalnpnmekjbajopld-Default)$",
    },
    immediate = true,
    workspace = "4",
    fullscreen = true,
})

-- GeForce NOW
hl.window_rule({
    match = {
        class = "^(chrome-play.geforcenow.com__mall_-Default)$",
    },
    workspace = "4",
    fullscreen = true,
    immediate = true,
})

