# Amazon Luna
windowrule = match:class ^(chrome-mdjpfbokiopdhidmalnpnmekjbajopld-Default)$, immediate on
windowrule = match:class ^(chrome-mdjpfbokiopdhidmalnpnmekjbajopld-Default)$, workspace 4
windowrule = match:class ^(chrome-mdjpfbokiopdhidmalnpnmekjbajopld-Default)$, fullscreen on

# GeForce NOW
windowrule = match:class ^(chrome-play.geforcenow.com__mall_-Default)$, workspace 4
windowrule = match:class ^(chrome-play.geforcenow.com__mall_-Default)$, fullscreen on
windowrule = match:class ^(chrome-play.geforcenow.com__mall_-Default)$, immediate on
