-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(cstrike_linux64)$",
    },
    immediate = true,
    render_unfocused = true,
    content = "game",
    workspace = "4",
})

