-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(CurseForge)$",
    },
    immediate = true,
    workspace = "7",
    content = "game",
})

