-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    render_unfocused = true,
    immediate = true,
    min_size = "800 600",
})

