windowrule = match:class *(gamescope)$, immediate on
windowrule = match:class *(gamescope)$, render_unfocused on
windowrule = match:class *(gamescope)$, float on
windowrule = match:class *(gamescope)$, fullscreen on
windowrule = match:class *(gamescope)$, content game
windowrule = match:class *(gamescope)$, workspace 4
