-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "*(gamescope)$",
    },
    immediate = true,
    render_unfocused = true,
    float = true,
    fullscreen = true,
    content = "game",
    workspace = "4",
})

