windowrule = match:class ^(HytaleClient)$, immediate on
windowrule = match:class ^(HytaleClient)$, render_unfocused on
windowrule = match:class ^(HytaleClient)$, fullscreen on
windowrule = match:class ^(HytaleClient)$, content game
windowrule = match:class ^(HytaleClient)$, workspace 4
