-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(localsend)$",
    },
    float = true,
    size = "423 614",
    move = "1478 54",
})

