-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(mxw-ui)$",
    },
    size = "415 400",
    float = true,
    pseudo = true,
})

-- windowrule = plugin:hyprbars:bar_color $base01, class:^(mxw-ui)$
