-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(chrome-www.nerdfonts.com__cheat-sheet-Default)$",
    },
    float = true,
    size = "1000 700",
})

