-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(chrome-photopea.com__-Default)$",
    },
    immediate = true,
})

-- # windowrule =  decorate off
