-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        title = "^(Protontricks)$",
    },
    float = true,
    rounding = 0,
})

-- windowrule = match:class ^(zenity) title:^(Protontricks)$, decorate off
