-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(protonvpn-app)$",
    },
    float = true,
    center = true,
    immediate = true,
    size = "400 600",
})

-- # windowrule =  decorate off
