-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(SGDBoop)$",
    },
    stay_focused = true,
    float = true,
    center = true,
})

