-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^([Ss]potify)$",
    },
    immediate = true,
})

-- # windowrule =  decorate off
