windowrule = match:class ^(steam)$, min_size 1 1
windowrule = match:title ^(Friends List)$, float on
windowrule = match:title ^(Add Non-Steam Game)$, float on
windowrule = match:title ^(Friends List)$, size 300 700
windowrule = match:class ^(steam_app_0)$, opacity 1 1
windowrule = match:class ^(steam_app_0)$, workspace 4


windowrule = match:class *(steam)$, immediate on
windowrule = match:class *(steam)$, render_unfocused on
windowrule = match:class *(steam)$, fullscreen on
windowrule = match:class *(steam)$, content game
windowrule = match:class *(steam)$, workspace 4
