-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(steam)$",
    },
    min_size = "1 1",
})

hl.window_rule({
    match = {
        title = "^(Friends List)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Add Non-Steam Game)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Friends List)$",
    },
    size = "300 700",
})

hl.window_rule({
    match = {
        class = "^(steam_app_0)$",
    },
    opacity = "1 1",
    workspace = "4",
})

hl.window_rule({
    match = {
        class = "*(steam)$",
    },
    immediate = true,
    render_unfocused = true,
    fullscreen = true,
    content = "game",
    workspace = "4",
})

