-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(org.gnome.SystemMonitor)$",
    },
    float = true,
    pin = true,
    pseudo = true,
})

-- windowrule = plugin:hyprbars:bar_color $base01, class:^(org.gnome.SystemMonitor)$
