windowrule {
    name = sink-switcher
    match:class = ^(sinkswitch)$
    float = yes
    pin = yes
    size = 400 120
    opacity = 1 1
    move = 1512 904
    move = 1512 53
    rounding = 0
}

windowrule {
    name = wifi-switcher
    match:class = ^(wifi)$
    float = yes
    pin = yes
    size = 400 488
    opacity = 1 1
    move = 1500 536
    move = 1180 53
    rounding = 0
}

windowrule {
    name = bluetooth-switcher
    match:class = ^(bluetooth)$
    float = yes
    pin = yes
    size = 400 488
    opacity = 1 1
    move = 1512 536
    move = 1310 53
    rounding = 0
}

windowrule {
    name = floating-fetch
    match:class = ^(fetch)$
    float = yes
    pin = yes
    size = 375 220
    opacity = 1 1
    rounding = 0
}

windowrule {
    name = floating-window
    match:class = ^(float)$
    float = yes
    pin = yes
    opacity = 1 1
    rounding = 0
}

windowrule {
    name = floating-no-pin
    match:class = ^(float-no-pin)$
    float = yes
    pin = no
    opacity = 1 1
    rounding = 0
}

windowrule {
    name = pip
    match:tag = pip
    min_size = 1 1
    size = 480 270
    move = 1320 8
    size = 592 269
    opacity = 1 1
    border_size = 3
    rounding = 0
    keep_aspect_ratio = no
    no_initial_focus = yes
    decorate = yes
    float = yes
    pin = yes
}
