-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        title = "^(winetricks)$",
    },
    rounding = 0,
})

hl.window_rule({
    match = {
        title = "^(Winetricks.*)$",
    },
    rounding = 0,
})

