theme = "base16_terminal"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true


[keys.normal]
C-s = ":w"
";" = "command_mode"
